version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
      args:
        API_KEY: ${API_KEY}
        API_DB_URL: ${API_DB_URL}
        CLOUDINARY_NAME: ${CLOUDINARY_NAME}
        CLOUDINARY_KEY: ${CLOUDINARY_KEY}
        CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
        CLOUDINARY_URL: ${CLOUDINARY_URL}
    container_name: fs-freelance-app-api
    restart: always
    volumes:
      - ./api:/app
      - .env:/app/env/.env
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      # - HOST=http://fs-app.loc
      - API_DB_URL=mongodb://${API_DB_USER}:${API_DB_PASSWORD}@api_db:27017/blog?authSource=admin
      - API_KEY=${API_KEY}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
      - CLOUDINARY_URL=cloudinary://${CLOUDINARY_KEY}:${CLOUDINARY_SECRET}@${CLOUDINARY_NAME}
      ##- AUTH_API_URL=http://auth:5001
      # command: >
      #   pwsh Set API_KEY=${API_KEY}  && Set API_DB_URL=${API_DB_URL} && Set CLOUDINARY_NAME=${CLOUDINARY_NAME} && Set CLOUDINARY_KEY=${CLOUDINARY_KEY} && Set CLOUDINARY_SECRET=${CLOUDINARY_SECRET} && Set CLOUDINARY_URL=${CLOUDINARY_URL}

    depends_on:
      - api_db
    networks:
      - fs-freelance-app-network
    tty:
      true  
    # healthcheck:
    #   test: curl --fail http://localhost:5000/ready || exit 1
    #   interval: 5s
    #   timeout: 5s
    #   start_period: 10s
    #   retries: 50
  frontend:
    restart: always
    ports:
    - 3000:3000 
    build:
      dockerfile: ./Dockerfile.prod
      context: ./frontend
      args:
        NODE_VERSION: ${NODE_VERSION}
        NGINX_HOST: ${NGINX_HOST}
        BLOG_API_URL: ${BLOG_API_URL}
        API_KEY: ${API_KEY}
        AUTH_API_URL: ${AUTH_API_URL}
        AUTH_API_KEY: ${AUTH_API_KEY}
        APP_NAME: ${APP_NAME}
        ADMIN_EMAILS: ${ADMIN_EMAILS}
        CLIENT_URL: ${CLIENT_URL}
    environment:
      - HOST=${PROD_NGINX_HOST}
      - API_KEY=${API_KEY}
      - BLOG_API_URL=${BLOG_API_URL}
      - AUTH_API_URL=${AUTH_API_URL}
      - AUTH_API_KEY=${AUTH_API_KEY}
      - APP_NAME=${APP_NAME}
      - APP_DOMAIN=${APP_DOMAIN}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - NEXT_PUBLIC_CLIENT_URL=${NEXT_PUBLIC_CLIENT_URL}
      - .env:/usr/src/app/.env.local
    container_name: fs-freelance-app-frontend
    networks:
      - fs-freelance-app-network
    tty:
      true
    # depends_on:
    #   api:
    #     condition: service_healthy
    # healthcheck:
    #   test: curl --fail http://localhost:3000/api/healthcheck || exit 1  # Update the healthcheck URL here
    #   interval: 10s
    #   timeout: 10s
    #   start_period: 30s
    #   retries: 50
  auth:
    build:
      dockerfile: ./Dockerfile
      context: ./auth
    container_name: fs-freelance-app-auth
    restart: unless-stopped
    volumes:
      - .env:/app/.env
    environment:
     AUTH_API_PORT: 5001
     AUTH_API_KEY: ${AUTH_API_KEY}
     AUTH_JWT_SECRET: ${AUTH_JWT_SECRET}
     SMTP_HOST: ${SMTP_HOST}
     SMTP_PORT: ${SMTP_PORT}
     SMTP_LOGIN: ${SMTP_LOGIN}
     SMTP_PASSWORD: ${SMTP_PASSWORD}

    ports:
      - 5001:5001
    networks:
      - fs-freelance-app-network
  api_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${API_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${API_DB_PASSWORD}
    #command: mongo
    container_name: fs-freelance-app-db
    volumes:
      - mongodb_api:/data/db
      - ./data/api-db/backup:/backup/
    networks:
      - fs-freelance-app-network
  nginx:
    restart: unless-stopped
    depends_on:
      - api
      - auth
    build:
      dockerfile: ./Dockerfile.prod
      args:
        NGINX_HOST: ${NGINX_HOST}
      context: ./nginx
    container_name: fs-freelance-app-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/configs/nginx.conf.prod:/etc/nginx/templates/default.conf.template
      - .env:/etc/nginx/environment/.env
    environment:
      - NGINX_HOST=${PROD_NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - NGINX_EXPOSED_PORT=${NGINX_EXPOSED_PORT}
    command: >
      bin/bash -c "source /etc/nginx/environment/.env && envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/templates/default.conf.template > etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
    # labels:
    #   - traefik.backend=sample
    #   ##- traefik.frontend.rule=Host:sample-docker.com
    #   - traefik.docker.network=fs-freelance-app-external-network
    #   - traefik.port=80
    networks:
      # - fs-freelance-app-external-network
      - fs-freelance-app-network
volumes:
  mongodb_api: null
networks:
  # fs-freelance-app-external-network:
  #   external: true
  fs-freelance-app-network:
    driver: bridge
    external: false
