version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile.development
    ports:
      - "5000:5000" #dev-port-http
      - "5001:5001" #dev-port-https
    volumes:
      - ./api:/app
      - .env:/app/env/.env
