version: "3.9"
services:
  frontend:
    # frontend will have no data (api has to be available before FE build starts
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    command: npm run dev
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src  
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile.development
    ports:
     - "5000:5000" #dev-port-http
    #  - "5001:5001" #dev-port-https
    environment:
      - PORT=5000
    volumes:
      - ./api:/app
      - .env:/app/env/.env
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/configs/nginx.conf.dev:/etc/nginx/templates/default.conf.template

    environment:
      - NGINX_HOST=${DEV_NGINX_HOST}
    build: 
      dockerfile: ./Dockerfile.dev
      context: ./nginx
      args:
        NGINX_HOST: ${NGINX_HOST}



